stages:
  - docker
  - mirror

build_gitlab:
  image: quay.io/containers/buildah:latest
  stage: docker
  script:
  - buildah login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - buildah pull $CI_REGISTRY_IMAGE:latest || true
  - >
    buildah bud --pull --layers
    --tag $CI_REGISTRY_IMAGE:latest
    --cache-from $CI_REGISTRY_IMAGE:latest .
  - buildah push $CI_REGISTRY_IMAGE:latest

mirror_github:
  image: quay.io/containers/buildah:latest
  stage: mirror
  script:
  - buildah login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - buildah pull $CI_REGISTRY_IMAGE:latest || true
  - buildah login -u $GITREPOUSER -p $GITREPOTOKEN $GITHUB_REGISTRY
  - buildah tag $CI_REGISTRY_IMAGE:latest $GITHUB_REGISTRY_IMAGE:latest 
  - buildah push $GITHUB_REGISTRY_IMAGE:latest

