stages:
  - docker
  - mirror

build_gitlab:
  image: docker:latest
  stage: docker
  services:
  - docker:dind
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker pull $CI_REGISTRY_IMAGE:latest || true
  - >
    docker build --pull
    --tag $CI_REGISTRY_IMAGE:latest
    --cache-from $CI_REGISTRY_IMAGE:latest .
  - docker push $CI_REGISTRY_IMAGE:latest

mirror_github:
  image: docker:latest
  stage: mirror
  services:
  - docker:dind
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker pull $CI_REGISTRY_IMAGE:latest || true
  - docker login -u $GITREPOUSER -p $GITREPOTOKEN $GITHUB_REGISTRY
  - docker tag $CI_REGISTRY_IMAGE:latest $GITHUB_REGISTRY_IMAGE:latest 
  - docker push $GITHUB_REGISTRY_IMAGE:latest

